### ISSUE TITLE
Atom complains about deprecated call

### ISSUE THREAD

**Issue by serkandurusoy** [awatson1978/meteor-api#11]
This is what I get when I click "create issue on github repo":

Subject:
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

Detail:
In stylesheets/meteor-color-coding.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by awatson1978** [comment]
Where exactly are you finding the 'create issue on github repo' link?

**Comment by serkandurusoy** [comment]
Oh sorry. Atom ships with  package called deprecation cop. It shows a yellow warning sign on the bottom right corner, right next to the updated packages count.

When you click on the warning sign, the deprecation cop tab opens up with a list of depracated calls grouped by the packages that have made them. Meteor-api is in the list and right next to the warning on that list, there is a create issue on githup repo link.

**Comment by awatson1978** [comment]
Finally got this squared away!  30+ people reported it, and nobody was able to submit a pullrequest.  Wound up needing to change ``atom-text-editor`` to ``atom-text-editor::shadow``.  A one-word fix!  XD

Update 2.16.0 should be available...
