### ISSUE TITLE
Can't find 'Orbit'

### ISSUE THREAD

**Issue by mdamjanic7** [awatson1978/meteor-api#13]
In [Readme.md](https://github.com/awatson1978/meteor-api/blob/master/README.md) **Orbit** is mentioned as one of the recommended atom packages, but I can't find it. Should the readme be updated, or an I doing something wrong?

**Comment by awatson1978** [comment]
Great question!  I'm not sure what happened to Orbit.  I'm going to clean up the Readme, as Orbit seems to have been deprecated....
