### ISSUE TITLE
Feature request: CoffeeScript version :)

### ISSUE THREAD

**Issue by CaptSaltyJack** [awatson1978/meteor-api#30]
Title says it all. Whenever you get around to it! (I'll keep an eye out)

**Comment by awatson1978** [comment]
Already included.  Look for KoffeeScript.  :)

**Comment by CaptSaltyJack** [comment]
D'oh! Sorry, the spelling threw me off.. ha. Thank you!

**Comment by awatson1978** [comment]
No problem.  It's spelled with a K because in the config panel I wanted Javascript first, and it orders things alphabetically.
