### ISSUE TITLE
Warning message in Atom

### ISSUE THREAD

**Issue by doru87** [awatson1978/meteor-api#36]
In `stylesheets\meteor-color-coding.less`: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

Not urgent i guess, but if you get the chance you may want to refactor the less file a bit. Cheers

**Comment by awatson1978** [comment]
Should be fixed in 2.16.0
