### ISSUE TITLE
Automatically apply "Javascript (Meteor)" to .js files?

### ISSUE THREAD

**Issue by steph643** [awatson1978/meteor-api#5]
Hi Abigail,
It's probably more of an Atom question, but did you find a way to automatically apply the "Javascript (Meteor)" grammar to all .js file? Right now it seems I'm obliged to apply it again each time I open a file... Same issue with the "Handlebar" grammar on .html files.
Thanks,

**Comment by awatson1978** [comment]
As of 2.16.0, solution is to disable the ``language-javascript`` package, and Atom will default to parsing javascript with the Javascript (Meteor) grammar set.  :)
