### ISSUE TITLE
Deprecated selectors in meteor-api - stylesheets/meteor-color-coding.less

### ISSUE THREAD

**Issue by jamc92** [awatson1978/meteor-api#50]
In stylesheets/meteor-color-coding.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by awatson1978** [comment]
Should be fixed in 2.216.0
