### ISSUE TITLE
Coffee Syntax Upgrades

### ISSUE THREAD

**Issue by ccorcos** [awatson1978/meteor-api#61]
Hey, I don't have any idea how to build syntax highlighters, but it would be nice if the "Koffeescript (Meteor)" highlighter would highlight "and" "or" "not" "?" "is" "isn't"

**Comment by awatson1978** [comment]
Hi.  It's mostly a matter of writing regexes.  Look in your ``~/.atom/packages`` directory, and you should see the ``meteor-api`` package.  Tinker with it a bit, and if you get something to work, drop me a line and I'll add it in!

**Comment by ccorcos** [comment]
Hmm. So it seems that "keyword.operator.coffee" is what I'm looking for and my syntax highlighter doesnt color it.  So this isn't an issue with this grammar (still figuring out how all this works).

I have a custom stylesheet though. Any ideas how I can somehow link the `keyword.operator.coffee` to color like a `keyword.control.coffee`?
